In [1]:
from keras.models import Sequential
from keras.layers import LSTM, Dense
from keras.utils.np_utils import to_categorical
import keras
import numpy as np
import random

Using TensorFlow backend.


In [2]:
'''logger = keras.callbacks.TensorBoard(
    log_dir = "logs", # log directory
    write_graph = True, # logs structure of model
    histogram_freq =5 # logs stats after every five passes
)'''

'logger = keras.callbacks.TensorBoard(\n    log_dir = "logs", # log directory\n    write_graph = True, # logs structure of model\n    histogram_freq =5 # logs stats after every five passes\n)'

In [3]:
def context_check(context,cue,probe):
    if context == 0:
        if cue == 0:
            if probe == 0:
                return '1AX'
            elif probe == 1:
                return '1AY'
        elif cue == 1:
            if probe == 0:
                return '1BX'
            elif probe == 1:
                return '1BY'
    elif context == 1:
        if cue == 0:
            if probe == 0:
                return '2AX'
            elif probe == 1:
                return '2AY'
        elif cue == 1:
            if probe == 0:
                return '2BX'
            elif probe == 1:
                return '2BY'

In [4]:
context_check(1,0,1)

'2AY'

In [5]:
def generate_data(sample_size):
    # validation data
    samples = []
    labels = []
    for i in range(sample_size):
        context = random.randrange(2)
        cue = random.randrange(2)
        probe = random.randrange(2)
        seq = [context,cue,probe]
        samples.append(seq)
        
        check = context_check(context,cue,probe)
        if check=='1AX' or check=='2BY':
            labels.append(0)
        else:
            labels.append(1)
    return np.array(samples),np.array(labels)

In [39]:
data_dim = 1
timesteps = 3
num_classes = 2

# expected input data shape: (batch_size, timesteps, data_dim)
model = Sequential()
model.add(LSTM(32, return_sequences=True,input_shape=(timesteps, data_dim),name='layer_1'))  # returns a sequence of vectors of dimension 32
model.add(LSTM(32, return_sequences=True,name='layer_2'))  # returns a sequence of vectors of dimension 32
model.add(LSTM(32,name='layer_3'))  # return a single vector of dimension 32
model.add(Dense(2, activation='softmax',name='output_layer'))

model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

# Generate dummy training data
#x_train = np.random.random((1000, timesteps, data_dim))
#y_train = np.random.random((1000, num_classes))
x_train,y_train = generate_data(10000)
x_train = x_train.reshape(10000,timesteps,data_dim)
y_train = to_categorical(y_train,num_classes=num_classes)

# Generate dummy validation data
#x_val = np.random.random((100, timesteps, data_dim))
#y_val = np.random.random((100, num_classes))
x_test,y_test = generate_data(1000)
x_test = x_test.reshape(1000,timesteps,data_dim)
y_test = to_categorical(y_test,num_classes=num_classes)
model.fit(x_train, y_train,
          batch_size=64, epochs=20,
          validation_data=(x_test, y_test)
          #callbacks=[logger]
         )

score = model.evaluate(x=x_test, y=y_test)
#for i in range(len(model.metrics_names)):
#    print(str(model.metrics_names[i]) + ": " + str(score[i]))


Train on 10000 samples, validate on 1000 samples
Epoch 1/20
10000/10000 [==============================] - 8s - loss: 0.5715 - acc: 0.7491 - val_loss: 0.5283 - val_acc: 0.7790
Epoch 2/20
10000/10000 [==============================] - 5s - loss: 0.5503 - acc: 0.7481 - val_loss: 0.4827 - val_acc: 0.7790
Epoch 3/20
10000/10000 [==============================] - 5s - loss: 0.2559 - acc: 0.8967 - val_loss: 0.0386 - val_acc: 1.0000
Epoch 4/20
10000/10000 [==============================] - 5s - loss: 0.0083 - acc: 1.0000 - val_loss: 5.4021e-05 - val_acc: 1.0000
Epoch 5/20
10000/10000 [==============================] - 5s - loss: 6.9405e-04 - acc: 0.9994 - val_loss: 2.4792e-06 - val_acc: 1.0000
Epoch 6/20
10000/10000 [==============================] - 5s - loss: 8.1023e-04 - acc: 1.0000 - val_loss: 7.2003e-07 - val_acc: 1.0000
Epoch 7/20
10000/10000 [==============================] - 5s - loss: 0.0011 - acc: 0.9992 - val_loss: 1.6642e-06 - val_acc: 1.0000
Epoch 8/20
10000/10000 [==============

In [37]:
predictions = model.predict(x_test,verbose=1,batch_size=50)

1000/1000 [==============================] - 0s     


In [38]:
print(predictions)

[[  4.18637699e-14   1.00000000e+00]
 [  3.66275508e-08   1.00000000e+00]
 [  9.99999881e-01   6.23413356e-08]
 ..., 
 [  9.99999881e-01   6.23413356e-08]
 [  1.00000000e+00   3.38460779e-08]
 [  8.60752820e-08   9.99999881e-01]]


In [9]:
A==C

True

In [10]:
x,y = generate_data(10)

In [11]:
x

array([[1, 1, 1],
       [1, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [1, 1, 0]])

In [12]:
y

array([0, 1, 1, 1, 1, 0, 1, 0, 1, 1])

In [13]:
x_train = np.random.random_integers(0,1,size=(1000,timesteps,data_dim))

/Users/arthurwilliams/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 1 + 1) instead
  if __name__ == '__main__':


In [14]:
x_train[0]

array([[0],
       [0],
       [0]])

In [23]:
x_test = np.random.randint(2,size=(100,timesteps,data_dim))
y_test = np.random.randint(2,size=100)
y_test = to_categorical(y_test,num_classes=num_classes)

In [24]:
x_test

array([[[1],
        [1],
        [1]],

       [[1],
        [0],
        [0]],

       [[1],
        [0],
        [0]],

       [[1],
        [0],
        [1]],

       [[0],
        [1],
        [0]],

       [[0],
        [1],
        [0]],

       [[0],
        [1],
        [1]],

       [[1],
        [0],
        [1]],

       [[0],
        [1],
        [1]],

       [[1],
        [0],
        [0]],

       [[1],
        [1],
        [0]],

       [[0],
        [1],
        [1]],

       [[0],
        [1],
        [1]],

       [[1],
        [0],
        [0]],

       [[0],
        [1],
        [0]],

       [[0],
        [1],
        [1]],

       [[0],
        [1],
        [1]],

       [[1],
        [0],
        [1]],

       [[1],
        [0],
        [1]],

       [[0],
        [1],
        [0]],

       [[1],
        [1],
        [1]],

       [[1],
        [0],
        [0]],

       [[1],
        [0],
        [1]],

       [[0],
        [1],
        [1]],

       [[0],
   

In [25]:
y_test

array([[ 1.,  0.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 1.,

In [20]:
x_train,y_train = generate_data(1000)
x_train = x_train.reshape(1000,timesteps,data_dim)
y_train = to_categorical(y_train,num_classes=num_classes)

In [18]:
x_train

array([[[0],
        [1],
        [0]],

       [[0],
        [0],
        [0]],

       [[0],
        [1],
        [0]],

       ..., 
       [[0],
        [1],
        [0]],

       [[1],
        [0],
        [0]],

       [[0],
        [1],
        [1]]])

In [21]:
y_train

array([[ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       ..., 
       [ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  1.]])